# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SKGO30EURQcGOceqxwBIYuSq5cnvT3QB
"""

import pandas as pd

from google.colab import files
files.upload()

df = pd.read_excel('CPI_time_series_March_2025.xls', sheet_name='All Rwanda', skiprows=3)

df.to_csv('rwanda_cpi.csv', index=False)

df

df.drop([1,3,4,5,6,7,19,20]).dropna().reset_index()

df = df.drop([1,3,4,5,6,7,19,20]).dropna().reset_index()
df

df.drop(columns=['index','Unnamed: 0','Unnamed: 1','Unnamed: 2'])

df = df.drop(columns=['index','Unnamed: 0','Unnamed: 1','Unnamed: 2'])

df.rename(columns={'Unnamed: 3':'Category'}, inplace=True)

df

df.set_index('Category')
df = df.set_index('Category')

df

date_cols = [c for c in df.columns if c not in ['Category', 'Weights']]

df.reset_index()
df= df.reset_index()

df.melt(
    id_vars= ['Category','Weights'],
    var_name='Date',
    value_vars= date_cols,
    value_name='cpi_value')

df_long = df.melt(
              id_vars= ['Category','Weights'],
              var_name='Date',
              value_vars= date_cols,
              value_name='cpi_value')

df_long['Date'] = pd.to_datetime(df_long['Date'])

df_long['Year'] = df_long['Date'].dt.year

df_long['Month'] = df_long['Date'].dt.month

df_long = df_long.dropna()

df_long = df_long.sort_values(['Category', 'Date'])

df_long.to_csv("data/rwanda_cpi_clean.csv", index=False)